train:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Identity

inference:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torch.nn.Identity

